# Generated by Django 3.2.6 on 2021-08-22 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='added_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='shows',
            name='user_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='shows',
            name='user_reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
