# Generated by Django 3.2.6 on 2021-08-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_zone', '0002_auto_20210822_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='reviews',
        ),
    ]
