# Generated by Django 3.2.6 on 2021-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_zone', '0003_remove_users_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
